"""Core agent: 5-phase pipeline (requirements -> parts -> plan -> generate -> repair)."""

import hashlib
import json
import logging
import re
import sys
from pathlib import Path

from . import config
from .llm import create_chat
from .prompts import (
    REQUIREMENTS_PROMPT,
    PARTS_PROMPT,
    DESIGN_PLAN_PROMPT,
    DECL_GENERATION_PROMPT,
    REPAIR_PROMPT,
    COMPLETENESS_VERIFY_PROMPT,
)
from .datasheet_to_decl import convert_datasheet_to_decl, first_component_name_from_decl
from .tools import (
    TOOL_DEFINITIONS,
    TOOL_DISPATCH,
    validate_decl_structured,
    _fix_common_issues,
    save_to_stdlib,
    get_stdlib_component_decl,
    extract_requires_from_decl,
    _expand_decl_imports,
)

logger = logging.getLogger(__name__)

_DECL_FENCE_RE = re.compile(r"```(?:decl)?\s*\n(.*?)```", re.DOTALL)
_JSON_FENCE_RE = re.compile(r"```(?:json)?\s*\n(.*?)```", re.DOTALL)
_SYSTEM_IMPORT_RE = re.compile(r"^\s*import\s+<([^>]+)>\s*$", re.MULTILINE)

# Tools for Phase 2 only (parts discovery + save datasheet-derived DECL to stdlib)
PARTS_PHASE_TOOL_NAMES = (
    "list_stdlib", "read_stdlib_file", "search_parts", "get_part_datasheet",
    "read_datasheet_pages", "save_to_stdlib",
)
PARTS_PHASE_TOOLS = [t for t in TOOL_DEFINITIONS if t["function"]["name"] in PARTS_PHASE_TOOL_NAMES]
PARTS_PHASE_DISPATCH = {k: v for k, v in TOOL_DISPATCH.items() if k in PARTS_PHASE_TOOL_NAMES}

def _convert_datasheet_to_decl_and_save(
    datasheet_text: str,
    url: str,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> None:
    """Convert datasheet excerpt to DECL and save to stdlib. Uses datasheet_to_decl module. Does not raise."""
    decl = convert_datasheet_to_decl(
        datasheet_text,
        url=url,
        backend=backend,
        model=model,
        ollama_url=ollama_url,
        max_attempts=6,
    )
    if not decl:
        # If datasheet conversion fails, use a deterministic built-in autogen for
        # common parts so the main flow can continue without manual stdlib edits.
        url_upper = (url or "").upper()
        fallback_import = None
        if "ATTINY85" in url_upper:
            fallback_import = "components/ATTINY85_20SU.decl"
        elif "USB" in url_upper:
            fallback_import = "components/USB_Connector.decl"
        if fallback_import:
            autogen_decl = _autogen_real_part_decl_from_import(fallback_import)
            if autogen_decl:
                autogen_rel = f"components/agent/generated/{Path(fallback_import).name}"
                try:
                    result = save_to_stdlib(autogen_rel, autogen_decl)
                    out = json.loads(result) if result.strip().startswith("{") else {}
                    if out.get("ok"):
                        _log_step(f"Saved fallback autogenerated DECL to stdlib: {autogen_rel}")
                        return
                    logger.warning("Datasheet fallback autogen save failed: %s", out.get("error", result))
                except Exception as exc:
                    logger.warning("Datasheet fallback autogen failed: %s", exc)
        return
    short_hash = hashlib.sha256(url.encode()).hexdigest()[:12]
    fallback_path = f"components/agent/datasheet_{short_hash}.decl"
    main_name = first_component_name_from_decl(decl)
    save_path = f"components/agent/{main_name}.decl" if main_name else fallback_path
    try:
        result = save_to_stdlib(save_path, decl)
        out = json.loads(result) if result.strip().startswith("{") else {}
        if out.get("ok"):
            _log_step(f"Saved datasheet DECL to stdlib: {save_path}")
        else:
            logger.warning("Datasheet-to-DECL: save failed: %s", out.get("error", result))
    except Exception as exc:
        logger.warning("Datasheet-to-DECL save failed: %s", exc)


def _parts_dispatch_with_auto_save(
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> dict:
    """Phase 2 tool dispatch that auto-converts every downloaded datasheet to DECL and saves."""
    dispatch = dict(PARTS_PHASE_DISPATCH)
    original_get = dispatch["get_part_datasheet"]
    original_read_pages = dispatch["read_datasheet_pages"]

    def _datasheet_text_from_tool_payload(data: dict, url: str) -> str:
        """Build plain text for conversion from tool payloads."""
        if not isinstance(data, dict):
            return ""
        pages = data.get("pages")
        if isinstance(pages, dict):
            chunks: list[str] = []
            for k in sorted(pages.keys(), key=lambda x: int(x) if str(x).isdigit() else str(x)):
                v = pages.get(k)
                if isinstance(v, str) and v.strip():
                    chunks.append(v)
            if chunks:
                return "\n\n".join(chunks)
        text = data.get("text")
        if isinstance(text, str) and text.strip():
            return text
        return ""

    def wrapped_get_part_datasheet(url: str) -> str:
        # So you can see on stdout whether the tool was ever invoked (convert only runs if result has text and no error)
        print("[circuitd] get_part_datasheet called: url=", url[:80] if url else "", sep="", flush=True)
        logger.info("get_part_datasheet called (url=%s); will convert to DECL if response has text and no error", url)
        result = original_get(url=url)
        try:
            data = json.loads(result)
            if not isinstance(data, dict) or data.get("error"):
                logger.warning(
                    "Datasheet-to-DECL: skipping convert (invalid payload or error): error=%s",
                    data.get("error") if isinstance(data, dict) else "n/a",
                )
                return result

            convert_url = data.get("url", url)
            text = _datasheet_text_from_tool_payload(data, convert_url)

            # Some datasheets return an empty preview from get_part_datasheet; fetch
            # first pages explicitly to still materialize a component decl.
            if not text:
                total_pages = data.get("total_pages")
                if isinstance(total_pages, int) and total_pages > 0:
                    end_page = min(total_pages - 1, 5)
                    try:
                        pages_result = original_read_pages(
                            url=convert_url,
                            start_page=0,
                            end_page=end_page,
                        )
                        pages_data = json.loads(pages_result)
                        text = _datasheet_text_from_tool_payload(pages_data, convert_url)
                    except Exception as exc:
                        logger.warning("Datasheet-to-DECL: read_datasheet_pages fallback failed: %s", exc)

            if text:
                logger.info("Datasheet-to-DECL: converting for url=%s", convert_url)
                _convert_datasheet_to_decl_and_save(
                    text,
                    convert_url,
                    backend=backend,
                    model=model,
                    ollama_url=ollama_url,
                )
            else:
                logger.warning("Datasheet-to-DECL: skipping convert (no extractable text)")
        except (json.JSONDecodeError, TypeError):
            logger.warning("Datasheet-to-DECL: failed to parse result: %s", result[:200] if result else "")
        return result

    dispatch["get_part_datasheet"] = wrapped_get_part_datasheet
    return dispatch


def _extract_decl(text: str) -> str | None:
    """Extract the last fenced decl block from the assistant's response."""
    matches = _DECL_FENCE_RE.findall(text)
    if not matches:
        return None
    candidate = matches[-1].strip()
    if not candidate:
        return None
    if any(kw in candidate for kw in ("component ", "schematic ", "protocol ", "variant ")):
        return candidate
    return None


def _extract_json(text: str) -> dict | None:
    """Try to extract a JSON object from the response."""
    for pattern in [_JSON_FENCE_RE, re.compile(r"\{.*\}", re.DOTALL)]:
        for match in pattern.findall(text):
            candidate = match.strip() if isinstance(match, str) else match
            try:
                obj = json.loads(candidate)
                if isinstance(obj, dict):
                    return obj
            except (json.JSONDecodeError, TypeError):
                continue
    return None


def _sanitize_decl_identifier(name: str) -> str:
    """Return a DECL-safe identifier that starts with an alphabetic letter."""
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not cleaned or not cleaned[0].isalpha():
        cleaned = f"C_{cleaned}" if cleaned else "C_AutoComponent"
    return cleaned


def _placeholder_component_decl_from_import(import_path: str) -> str:
    """Build a minimal component decl for a missing stdlib component import."""
    stem = Path(import_path).stem
    comp_name = _sanitize_decl_identifier(stem)
    return (
        f"component {comp_name} {{\n"
        "  pins {\n"
        "    1: Passive as A\n"
        "    2: Passive as B\n"
        "  }\n"
        "}\n"
    )


def _autogen_real_part_decl_from_import(import_path: str) -> str | None:
    """Return an auto-generated DECL for known frequently-requested real parts."""
    stem_upper = Path(import_path).stem.upper()
    if "ATTINY85" in stem_upper:
        return (
            "import <protocols/uart.decl>\n\n"
            "component ATTINY85_20SU {\n"
            "  pins {\n"
            "    1: Input as RESET_N\n"
            "    2: Bidirectional as PB3\n"
            "    3: Bidirectional as PB4\n"
            "    4: PowerInput as GND\n"
            "    5: Bidirectional as PB0\n"
            "    6: Bidirectional as PB1\n"
            "    7: Bidirectional as PB2\n"
            "    8: PowerInput as VCC\n"
            "  }\n"
            "  features {\n"
            "    external UART0 using protocol UART role endpoint {\n"
            "      TX -> pin PB1\n"
            "      RX -> pin PB0\n"
            "    }\n"
            "  }\n"
            "}\n"
        )
    if "USB" in stem_upper and "CONNECTOR" in stem_upper:
        return (
            "component USB_Connector {\n"
            "  pins {\n"
            "    1: PowerInput as VBUS\n"
            "    2: PowerInput as GND\n"
            "    3: Bidirectional as DPLUS\n"
            "    4: Bidirectional as DMINUS\n"
            "    5: Bidirectional as CC1\n"
            "    6: Bidirectional as CC2\n"
            "  }\n"
            "}\n"
        )
    return None


def _normalize_instance_pin_aliases(decl_code: str) -> str:
    """Normalize common LLM pin aliases to canonical stdlib aliases by instance type."""
    instance_types: dict[str, str] = {}
    for m in re.finditer(r"instance\s+(\w+)\s*:\s*(\w+)", decl_code):
        instance_types[m.group(1)] = m.group(2)

    # Canonical aliases in this stdlib:
    # - Resistor: A/B
    # - Capacitor: positive/negative
    # - LED: anode/cathode
    alias_map: dict[str, dict[str, str]] = {
        "Resistor": {
            "PIN1": "A",
            "P1": "A",
            "PINA": "A",
            "POSITIVE": "A",
            "ANODE": "A",
            "PIN2": "B",
            "P2": "B",
            "PINB": "B",
            "NEGATIVE": "B",
            "CATHODE": "B",
        },
        "Capacitor": {
            "PIN1": "positive",
            "P1": "positive",
            "PINA": "positive",
            "A": "positive",
            "PIN2": "negative",
            "P2": "negative",
            "PINB": "negative",
            "B": "negative",
        },
        "LED": {
            "PIN1": "anode",
            "P1": "anode",
            "PINA": "anode",
            "POSITIVE": "anode",
            "PIN2": "cathode",
            "P2": "cathode",
            "PINB": "cathode",
            "NEGATIVE": "cathode",
        },
    }

    out = decl_code
    for inst_name, comp_type in instance_types.items():
        per_type = alias_map.get(comp_type)
        if not per_type:
            continue
        for wrong, right in per_type.items():
            out = re.sub(
                rf"\b{re.escape(inst_name)}\.{re.escape(wrong)}\b",
                f"{inst_name}.{right}",
                out,
                flags=re.IGNORECASE,
            )
    return out


def _looks_like_real_part_import(import_path: str) -> bool:
    """Heuristic: true when missing import name looks like a concrete part/device."""
    stem = Path(import_path).stem
    upper = stem.upper()
    if upper.startswith(("ATTINY", "ATMEGA", "STM", "CH32", "ESP", "RP2040", "USB_", "PIC", "LPC")):
        return True
    # Typical concrete part-like token: starts with uppercase family + digits
    # (e.g. W25Q128, LM1117, CH340G). Anchor at start to avoid numeric IDs
    # like 917_141B... being treated as strict real-part imports.
    return bool(re.match(r"^[A-Z]{2,}[A-Z0-9_]*\d", upper))


def _normalize_part_stem(stem: str) -> str:
    """Normalize part stem for fuzzy stdlib matching (package/reel suffix tolerant)."""
    # ATTINY85_20SUR -> ATTINY85_20, ATTINY85_20SU -> ATTINY85_20
    return re.sub(r"[A-Za-z]+$", "", stem.upper())


def _part_family_token(stem: str) -> str:
    """Extract comparable family token, e.g. ATTINY85V -> ATTINY85."""
    head = stem.upper().split("_", 1)[0]
    return re.sub(r"([A-Z]+\d+)[A-Z]*$", r"\1", head)


def _part_family_signature(stem: str) -> tuple[str, set[str]]:
    """Return (alpha_prefix, numeric groups) for fuzzy family matching."""
    s = stem.upper().replace("-", "_")
    alpha_match = re.match(r"([A-Z]+)", s)
    alpha = alpha_match.group(1) if alpha_match else ""
    nums = set(re.findall(r"\d+", s))
    return alpha, nums


def _find_stdlib_component_alias(import_path: str, stdlib_root: Path) -> str | None:
    """Find a close existing stdlib component for a missing real-part import."""
    target_stem = Path(import_path).stem
    target_norm = _normalize_part_stem(target_stem)
    target_family = _part_family_token(target_stem)
    target_alpha, target_nums = _part_family_signature(target_stem)
    candidates: list[str] = []
    for cand in (stdlib_root / "components").rglob("*.decl"):
        cand_stem = cand.stem
        cand_norm = _normalize_part_stem(cand_stem)
        cand_family = _part_family_token(cand_stem)
        cand_alpha, cand_nums = _part_family_signature(cand_stem)
        family_match = False
        if target_alpha and cand_alpha and target_alpha == cand_alpha:
            if target_nums and cand_nums and (target_nums & cand_nums):
                family_match = True
        if (
            cand_norm == target_norm
            or (target_family and cand_family == target_family)
            or family_match
        ):
            rel = cand.relative_to(stdlib_root).as_posix()
            candidates.append(rel)
    if len(candidates) == 1:
        return candidates[0]
    # Case-insensitive exact stem match as a secondary fallback.
    target_stem_upper = target_stem.upper()
    ci_matches = []
    for cand in (stdlib_root / "components").rglob("*.decl"):
        if cand.stem.upper() == target_stem_upper:
            ci_matches.append(cand.relative_to(stdlib_root).as_posix())
    if len(ci_matches) == 1:
        return ci_matches[0]
    return None


def _ensure_missing_component_import_files(decl_code: str) -> tuple[str, list[str]]:
    """Create missing imported component files in stdlib/components and rewrite imports."""
    stdlib_root = Path(config.STDLIB_PATH)
    if not stdlib_root.is_dir():
        return decl_code, []

    created: list[str] = []
    rewrites: dict[str, str] = {}
    component_dir = stdlib_root / "components"
    component_dir.mkdir(parents=True, exist_ok=True)

    seen: set[str] = set()
    for m in _SYSTEM_IMPORT_RE.finditer(decl_code):
        import_path = m.group(1).strip().replace("\\", "/")
        if import_path in seen:
            continue
        seen.add(import_path)

        target = (stdlib_root / import_path).resolve()
        if target.is_file():
            continue

        # Fail fast for real parts: these should exist in stdlib or be generated
        # explicitly, never substituted with generic placeholders.
        if import_path.startswith("components/") and _looks_like_real_part_import(import_path):
            alias = _find_stdlib_component_alias(import_path, stdlib_root)
            if alias:
                rewrites[import_path] = alias
                _log_step(
                    f"Resolved missing real-part import <{import_path}> to stdlib alias <{alias}>"
                )
                continue
            autogen = _autogen_real_part_decl_from_import(import_path)
            if autogen:
                autogen_rel = f"components/agent/generated/{Path(import_path).name}"
                autogen_abs = stdlib_root / autogen_rel
                autogen_abs.parent.mkdir(parents=True, exist_ok=True)
                autogen_abs.write_text(autogen, encoding="utf-8")
                rewrites[import_path] = autogen_rel
                created.append(autogen_rel)
                _log_step(
                    f"Auto-generated missing real-part component <{import_path}> at <{autogen_rel}>"
                )
                continue
            raise FileNotFoundError(
                "Missing stdlib component import looks like a real part and will not be "
                f"auto-placeholdered: <{import_path}>. "
                "Add/create the component declaration in stdlib first."
            )

        # Create placeholders only under components/agent/placeholders so we do not
        # silently pollute canonical stdlib component names with generic A/B pin stubs.
        fallback_rel = f"components/agent/placeholders/{Path(import_path).name}"
        fallback_abs = stdlib_root / fallback_rel
        if not fallback_abs.is_file():
            fallback_abs.parent.mkdir(parents=True, exist_ok=True)
            fallback_abs.write_text(_placeholder_component_decl_from_import(import_path), encoding="utf-8")
            created.append(fallback_rel)
        rewrites[import_path] = fallback_rel

    if not rewrites:
        return decl_code, created

    def _rewrite(match: re.Match) -> str:
        path = match.group(1).strip().replace("\\", "/")
        new_path = rewrites.get(path, path)
        return f"import <{new_path}>"

    updated = _SYSTEM_IMPORT_RE.sub(_rewrite, decl_code)
    return updated, created


def _mandatory_inventory_from_requirements(requirements: dict) -> list[dict]:
    """Build inventory-like list for completeness check from requirements JSON."""
    inventory: list[dict] = []
    for item in requirements.get("explicit_parts", []):
        name = item.get("name") or item.get("part")
        if name:
            inventory.append({"name": name, "purpose": item.get("reason", ""), "check_terms": [name]})
    for item in requirements.get("implied_blocks", []):
        name = item.get("name")
        if name:
            inventory.append({"name": name, "purpose": item.get("reason", ""), "check_terms": [name]})
    for item in requirements.get("support_components", []):
        name = item.get("name")
        if name:
            inventory.append({"name": name, "purpose": item.get("reason", ""), "check_terms": [name]})
    return inventory


def _normalize_for_match(text: str) -> str:
    """Collapse whitespace, underscores, and hyphens so 'Green LED' matches 'Green_LED'."""
    return re.sub(r"[\s_\-]+", "", text).lower()


def _check_completeness(decl_code: str, inventory: list[dict]) -> list[str]:
    """Check which inventory items are missing from the generated .decl code (heuristic: substring match)."""
    code_lower = decl_code.lower()
    code_normalized = _normalize_for_match(decl_code)
    missing = []
    for item in inventory:
        name = item.get("name", "")
        check_terms = item.get("check_terms", [name])
        found = any(
            term.lower() in code_lower or _normalize_for_match(term) in code_normalized
            for term in check_terms
        )
        if not found:
            missing.append(f"- {name}: {item.get('purpose', '(no description)')}")
    return missing


def _verify_completeness_with_llm(
    decl_code: str,
    heuristic_missing: list[str],
    requirements: dict,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> list[str]:
    """Ask LLM which heuristic 'missing' items are actually missing vs already present in DECL.
    Returns the list of items that are actually missing (for the add-missing step).
    """
    if not heuristic_missing:
        return []
    _log_phase_to_prompts_file("Completeness: LLM verification of missing items")
    chat = create_chat(
        backend, COMPLETENESS_VERIFY_PROMPT, tools=[], tool_dispatch={},
        model=model, ollama_url=ollama_url,
    )
    missing_blob = "\n".join(heuristic_missing)
    user_msg = (
        "Flagged as missing (from a simple text match; may be false positives):\n\n"
        f"{missing_blob}\n\n"
        "Requirements summary (for context):\n"
        + json.dumps(
            {
                "explicit_parts": requirements.get("explicit_parts", []),
                "implied_blocks": requirements.get("implied_blocks", []),
                "support_components": requirements.get("support_components", []),
            },
            indent=2,
        )
        + "\n\nDECL file to check:\n\n```decl\n"
        + decl_code
        + "\n```\n\n"
        "Output ONLY a JSON object with 'actually_missing' and 'already_present' arrays."
    )
    response = chat.send(user_msg)
    obj = _extract_json(response)
    if not obj or not isinstance(obj, dict):
        _log_step("Completeness verification: no valid JSON; treating all flagged as already present")
        return []
    actually_missing = obj.get("actually_missing") or []
    if not isinstance(actually_missing, list):
        actually_missing = []
    already_present = obj.get("already_present") or []
    if isinstance(already_present, list) and already_present:
        _log_step(f"Completeness verification: {len(already_present)} item(s) already present in DECL")
    if actually_missing:
        _log_step(f"Completeness verification: {len(actually_missing)} item(s) actually missing")
    return actually_missing


def _log_step(msg: str) -> None:
    logger.info(msg)
    print(f"  [{msg}]", file=sys.stderr)


def _log_phase_to_prompts_file(phase_label: str) -> None:
    """Write a phase header to the prompts log file so the next LLM block is identifiable."""
    path = getattr(config, "PROMPTS_LOG_PATH", None)
    if path is None:
        return
    try:
        from datetime import datetime, timezone
        with open(path, "a", encoding="utf-8") as f:
            f.write("\n")
            f.write("# " + "=" * 76 + "\n")
            f.write(f"# AGENT PHASE: {phase_label}\n")
            f.write("# " + "=" * 76 + "\n\n")
    except OSError as exc:
        logger.debug("Failed to write phase to prompts log: %s", exc)


# ---------------------------------------------------------------------------
# Phase 1: Requirements extraction
# ---------------------------------------------------------------------------

def _run_phase1_requirements(
    user_prompt: str,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> dict:
    _log_step("Phase 1: Requirements extraction")
    _log_phase_to_prompts_file("Phase 1: Requirements extraction")
    chat = create_chat(
        backend, REQUIREMENTS_PROMPT, tools=[], tool_dispatch={},
        model=model, ollama_url=ollama_url,
    )
    response = chat.send(user_prompt)
    obj = _extract_json(response)
    if not obj or not isinstance(obj, dict):
        _log_step("WARNING: No valid requirements JSON; using minimal brief")
        return {
            "functions": [],
            "constraints": [],
            "explicit_parts": [],
            "implied_blocks": [],
            "power_requirements": [],
            "interfaces": [],
            "support_components": [],
            "assumptions": [],
            "open_questions": [],
        }
    _log_step(f"Requirements: {len(obj.get('explicit_parts', []))} explicit, {len(obj.get('implied_blocks', []))} implied")
    return obj


# ---------------------------------------------------------------------------
# Phase 2: Part / stdlib discovery (with tool loop)
# ---------------------------------------------------------------------------

def _run_phase2_parts(
    requirements: dict,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> dict:
    _log_step("Phase 2: Part selection / library discovery")
    _log_phase_to_prompts_file("Phase 2: Part selection / library discovery")
    dispatch = _parts_dispatch_with_auto_save(backend=backend, model=model, ollama_url=ollama_url)
    chat = create_chat(
        backend, PARTS_PROMPT, PARTS_PHASE_TOOLS, dispatch,
        model=model, ollama_url=ollama_url,
    )
    user_msg = (
        "Design brief (use the tools to look up stdlib and parts, then output the selection JSON):\n"
        + json.dumps(requirements, indent=2)
    )
    response = chat.send(user_msg)
    obj = _extract_json(response)
    if not obj or not isinstance(obj, dict):
        _log_step("WARNING: No valid parts JSON; using empty selection")
        return {"selected_components": [], "nets_needed": [], "design_rules": [], "unresolved": []}
    _log_step(f"Parts: {len(obj.get('selected_components', []))} components selected")
    return obj


# ---------------------------------------------------------------------------
# Phase 3: Design plan
# ---------------------------------------------------------------------------

def _run_phase3_design_plan(
    requirements: dict,
    parts: dict,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> dict:
    _log_step("Phase 3: Design plan (connection plan)")
    _log_phase_to_prompts_file("Phase 3: Design plan (connection plan)")
    chat = create_chat(
        backend, DESIGN_PLAN_PROMPT, tools=[], tool_dispatch={},
        model=model, ollama_url=ollama_url,
    )
    user_msg = (
        "Requirements and selected parts. Output the connection plan JSON only.\n\n"
        "Requirements:\n" + json.dumps(requirements, indent=2) + "\n\n"
        "Parts:\n" + json.dumps(parts, indent=2)
    )
    response = chat.send(user_msg)
    obj = _extract_json(response)
    if not obj or not isinstance(obj, dict):
        _log_step("WARNING: No valid design plan JSON")
        return {"instances": [], "nets": [], "connections": [], "power_topology": [], "protocol_bindings": [], "checks": []}
    _log_step(f"Plan: {len(obj.get('instances', []))} instances, {len(obj.get('nets', []))} nets")
    return obj


# ---------------------------------------------------------------------------
# Phase 4: DECL generation
# ---------------------------------------------------------------------------

def _run_phase4_generate_decl(
    design_plan: dict,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> str | None:
    _log_step("Phase 4: DECL generation")
    _log_phase_to_prompts_file("Phase 4: DECL generation")
    chat = create_chat(
        backend, DECL_GENERATION_PROMPT, tools=[], tool_dispatch={},
        model=model, ollama_url=ollama_url,
    )
    user_msg = (
        "Emit only a ```decl code block containing the complete .decl file for this plan:\n\n"
        + json.dumps(design_plan, indent=2)
    )
    # Include stdlib component definitions so the LLM uses correct protocol pin mappings (e.g. SPI CLK/MOSI/MISO/SS)
    comp_types = set()
    for inst in design_plan.get("instances", []):
        c = inst.get("component")
        if isinstance(c, str):
            comp_types.add(c)
    stdlib_refs: list[str] = []
    for comp_name in sorted(comp_types):
        decl_content = get_stdlib_component_decl(comp_name)
        if decl_content:
            stdlib_refs.append(f"\n--- stdlib reference for {comp_name} (use these pins for protocol connections) ---\n{decl_content[:12000]}")
    if stdlib_refs:
        user_msg += "\n\nReference definitions from stdlib (protocol pin mappings must be respected):" + "\n".join(stdlib_refs)
    response = chat.send(user_msg)
    decl = _extract_decl(response)
    if decl:
        decl = _fix_common_issues(decl)
        decl = _normalize_instance_pin_aliases(decl)
        _log_step(f"Generated .decl ({len(decl)} chars)")
    else:
        _log_step("WARNING: No decl block in response")
    return decl


# ---------------------------------------------------------------------------
# Phase 5: Validator repair loop
# ---------------------------------------------------------------------------

def _run_phase5_repair_loop(
    decl_code: str,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> str:
    _log_step("Phase 5: Validation and repair")
    _log_phase_to_prompts_file("Phase 5: Validation and repair")
    decl_code = _normalize_instance_pin_aliases(_fix_common_issues(decl_code))
    chat = create_chat(
        backend, REPAIR_PROMPT, tools=[], tool_dispatch={},
        model=model, ollama_url=ollama_url,
    )
    try:
        decl, created = _ensure_missing_component_import_files(decl_code)
    except FileNotFoundError as exc:
        _log_step(f"ERROR: {exc}")
        raise SystemExit(1) from exc
    for rel in created:
        _log_step(f"Created missing stdlib import file: {rel}")
    for iteration in range(config.MAX_AGENT_ITERATIONS):
        human_output, structured_errors = validate_decl_structured(decl)
        is_ok = human_output.strip().startswith("OK:")

        if is_ok:
            _log_step("Validation passed")
            return decl

        if not structured_errors:
            # Avoid expensive churn when validator output has no machine-actionable
            # errors (for example, transient checker failures or nonstandard text).
            _log_step("Validation failed but no structured errors; stopping repair loop")
            return decl

        _log_step(f"Repair iteration {iteration + 1}: {len(structured_errors)} structured errors")
        err_blob = human_output
        if structured_errors:
            err_blob += "\n\nStructured errors (for repair):\n" + json.dumps(structured_errors, indent=2)
        user_msg = (
            "Fix the following DECL so it passes validation. Output ONLY a ```decl block.\n\n"
            "Validation output:\n" + err_blob + "\n\n"
            "Current DECL (fix the errors in it):\n\n```decl\n" + decl + "\n```"
        )
        response = chat.send(user_msg)
        repaired = _extract_decl(response)
        if not repaired:
            _log_step("No decl block in repair response; keeping last version")
            break
        decl = _normalize_instance_pin_aliases(_fix_common_issues(repaired))
    return decl


# ---------------------------------------------------------------------------
# Requires-aware completeness
# ---------------------------------------------------------------------------

def _check_requires_completeness(
    decl_code: str,
    *,
    backend: str,
    model: str | None,
    ollama_url: str | None,
) -> str:
    """Check that components' `requires` entries are satisfied in the schematic.

    Expands imports so that stdlib components' requires blocks are visible,
    then verifies that the schematic contains enough support parts.
    """
    try:
        sp = Path(config.STDLIB_PATH)
        expanded = _expand_decl_imports(decl_code, sp, stdlib_root=sp)
    except Exception:
        expanded = decl_code
    reqs = extract_requires_from_decl(expanded)
    if not reqs:
        return decl_code

    instance_types: dict[str, int] = {}
    for m in re.finditer(r"instance\s+\w+\s*:\s*(\w+)", decl_code):
        ctype = m.group(1)
        instance_types[ctype] = instance_types.get(ctype, 0) + 1

    missing_parts: list[str] = []
    for comp_type, attrs, count in reqs:
        actual = instance_types.get(comp_type, 0)
        if actual < count:
            attr_str = ", ".join(f"{k}={v}" for k, v in attrs.items())
            desc = f"{comp_type}"
            if attr_str:
                desc += f" ({attr_str})"
            missing_parts.append(f"- Need {count}x {desc}, have {actual}")

    if not missing_parts:
        _log_step("Requires check: all required support components present")
        return decl_code

    _log_step(f"Requires check: {len(missing_parts)} missing support requirement(s)")
    for m in missing_parts:
        _log_step(f"  {m}")

    _log_phase_to_prompts_file("Requires completeness: add missing support components")
    chat = create_chat(
        backend, REPAIR_PROMPT, tools=[], tool_dispatch={},
        model=model, ollama_url=ollama_url,
    )
    missing_text = "\n".join(missing_parts)
    user_msg = (
        "The .decl file below is valid but is missing required support components "
        "declared in `requires` blocks. Add the missing instances and connect them "
        "appropriately.\n\n"
        f"Missing requirements:\n{missing_text}\n\n"
        "Current .decl:\n\n"
        f"```decl\n{decl_code}\n```"
    )
    response = chat.send(user_msg)
    new_decl = _extract_decl(response)
    if not new_decl:
        _log_step("No decl block in response; keeping current version")
        return decl_code
    decl_code = _fix_common_issues(new_decl)
    decl_code = _run_phase5_repair_loop(
        decl_code, backend=backend, model=model, ollama_url=ollama_url,
    )
    return decl_code


# ---------------------------------------------------------------------------
# Main entry: 5-phase pipeline
# ---------------------------------------------------------------------------

def run_agent(
    prompt: str,
    output_path: str = "output.decl",
    *,
    backend: str | None = None,
    model: str | None = None,
    ollama_url: str | None = None,
) -> Path:
    """Run the 5-phase circuit design agent and write the result to *output_path*."""
    backend = backend or config.BACKEND

    # Phase 1: Requirements
    requirements = _run_phase1_requirements(
        prompt, backend=backend, model=model, ollama_url=ollama_url,
    )

    # Phase 2: Parts (with tools)
    parts = _run_phase2_parts(
        requirements, backend=backend, model=model, ollama_url=ollama_url,
    )

    # Phase 3: Design plan
    design_plan = _run_phase3_design_plan(
        requirements, parts, backend=backend, model=model, ollama_url=ollama_url,
    )

    # Phase 4: Generate DECL
    decl_code = _run_phase4_generate_decl(
        design_plan, backend=backend, model=model, ollama_url=ollama_url,
    )
    if not decl_code:
        print("Error: agent did not produce a .decl file.", file=sys.stderr)
        sys.exit(1)

    # Phase 5: Validate and repair until OK
    decl_code = _run_phase5_repair_loop(
        decl_code, backend=backend, model=model, ollama_url=ollama_url,
    )

    # Completeness loop: heuristic flags possible missing items; LLM verifies which are actually missing
    inventory = _mandatory_inventory_from_requirements(requirements)
    for completeness_iteration in range(config.MAX_AGENT_ITERATIONS):
        if not inventory:
            break
        heuristic_missing = _check_completeness(decl_code, inventory)
        if not heuristic_missing:
            break
        _log_step(f"Completeness: heuristic flagged {len(heuristic_missing)} item(s); verifying with LLM")
        actually_missing = _verify_completeness_with_llm(
            decl_code, heuristic_missing, requirements,
            backend=backend, model=model, ollama_url=ollama_url,
        )
        if not actually_missing:
            _log_step("Completeness: all flagged items already present in DECL; done")
            break
        _log_step(f"Completeness: {len(actually_missing)} required item(s) actually missing; asking LLM to add them")
        for m in actually_missing:
            _log_step(f"  {m}")
        _log_phase_to_prompts_file("Completeness: add missing components")
        chat = create_chat(
            backend, REPAIR_PROMPT, tools=[], tool_dispatch={},
            model=model, ollama_url=ollama_url,
        )
        missing_text = "\n".join(actually_missing)
        user_msg = (
            "The .decl file below is valid but INCOMPLETE. The following required components "
            "are MISSING from the schematic:\n\n"
            f"{missing_text}\n\n"
            "Add these components (define them as component if needed), add instances for them, "
            "and connect them appropriately. Output the complete corrected .decl in a ```decl block.\n\n"
            "Current .decl:\n\n"
            f"```decl\n{decl_code}\n```"
        )
        response = chat.send(user_msg)
        new_decl = _extract_decl(response)
        if not new_decl:
            _log_step("No decl block in response; keeping current version")
            break
        decl_code = _fix_common_issues(new_decl)
        # Re-validate in case the LLM introduced errors
        decl_code = _run_phase5_repair_loop(
            decl_code, backend=backend, model=model, ollama_url=ollama_url,
        )

    # Requires-aware completeness: check that all requires entries from components are satisfied
    decl_code = _check_requires_completeness(
        decl_code, backend=backend, model=model, ollama_url=ollama_url,
    )

    out = Path(output_path)
    out.write_text(decl_code + "\n")
    print(f"\nCircuit written to {out}")
    return out
